export const newestCollectibles = [
  {
    imageUrl: 'image/Phantz Club.svg',
    title: 'Phantz Club',
    timestamp: '1m ago',
    tokenid: '0x651s...shslf',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
  {
    imageUrl: 'image/Data Droidz.svg',
    title: 'Data Droidz',
    timestamp: '1m ago',
    tokenid: '0x651s...shslf',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
  {
    imageUrl: 'image/Bunny Punk.svg',
    title: 'Bunny Punk',
    timestamp: '1m ago',
    tokenid: '0x651s...shslf',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
  {
    imageUrl: 'image/Elastos Apes.svg',
    title: 'Elastos Apes',
    timestamp: '1m ago',
    tokenid: '0x651s...shslf',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
  {
    imageUrl: 'image/Ela Nugz.svg',
    title: 'Ela Nugz',
    timestamp: '1m ago',
    tokenid: '0x651s...shslf',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
];

export const latestTransactions = [
  {
    imageUrl: 'image/Phantz Club.svg',
    txhash: '0x651sdfddfsfs...shslf',
    timestamp: '1m ago',
    method: 'Transfer',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
  {
    imageUrl: 'image/Data Droidz.svg',
    txhash: '0x651sdfddfsfs...shslf',
    timestamp: '1m ago',
    method: 'Transfer',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
  {
    imageUrl: 'image/Bunny Punk.svg',
    txhash: '0x651sdfddfsfs...shslf',
    timestamp: '1m ago',
    method: 'Transfer',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
  {
    imageUrl: 'image/Elastos Apes.svg',
    txhash: '0x651sdfddfsfs...shslf',
    timestamp: '1m ago',
    method: 'Transfer',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
  {
    imageUrl: 'image/Ela Nugz.svg',
    txhash: '0x651sdfddfsfs...shslf',
    timestamp: '1m ago',
    method: 'Transfer',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
];
