export const newestCollectibles = [
  {
    imageUrl: '/image/Phantz Club.svg',
    collection: 'Phantz Club',
    timestamp: '1m ago',
    tokenid: '0x651s...shslf',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
  {
    imageUrl: '/image/Data Droidz.svg',
    collection: 'Data Droidz',
    timestamp: '1m ago',
    tokenid: '0x651s...shslf',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
  {
    imageUrl: '/image/Bunny Punk.svg',
    collection: 'Bunny Punk',
    timestamp: '1m ago',
    tokenid: '0x651s...shslf',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
  {
    imageUrl: '/image/Elastos Apes.svg',
    collection: 'Elastos Apes',
    timestamp: '1m ago',
    tokenid: '0x651s...shslf',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
  {
    imageUrl: '/image/Ela Nugz.svg',
    collection: 'Ela Nugz',
    timestamp: '1m ago',
    tokenid: '0x651s...shslf',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
  {
    imageUrl: '/image/Phantz Club.svg',
    collection: 'Phantz Club',
    timestamp: '1m ago',
    tokenid: '0x651s...shslf',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
  {
    imageUrl: '/image/Data Droidz.svg',
    collection: 'Data Droidz',
    timestamp: '1m ago',
    tokenid: '0x651s...shslf',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
  {
    imageUrl: '/image/Bunny Punk.svg',
    collection: 'Bunny Punk',
    timestamp: '1m ago',
    tokenid: '0x651s...shslf',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
  {
    imageUrl: '/image/Elastos Apes.svg',
    collection: 'Elastos Apes',
    timestamp: '1m ago',
    tokenid: '0x651s...shslf',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
  {
    imageUrl: '/image/Ela Nugz.svg',
    collection: 'Ela Nugz',
    timestamp: '1m ago',
    tokenid: '0x651s...shslf',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
  {
    imageUrl: '/image/Phantz Club.svg',
    collection: 'Phantz Club',
    timestamp: '1m ago',
    tokenid: '0x651s...shslf',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
  {
    imageUrl: '/image/Data Droidz.svg',
    collection: 'Data Droidz',
    timestamp: '1m ago',
    tokenid: '0x651s...shslf',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
  {
    imageUrl: '/image/Bunny Punk.svg',
    collection: 'Bunny Punk',
    timestamp: '1m ago',
    tokenid: '0x651s...shslf',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
  {
    imageUrl: '/image/Elastos Apes.svg',
    collection: 'Elastos Apes',
    timestamp: '1m ago',
    tokenid: '0x651s...shslf',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
  {
    imageUrl: '/image/Ela Nugz.svg',
    collection: 'Ela Nugz',
    timestamp: '1m ago',
    tokenid: '0x651s...shslf',
    gasfee: '0.0031464 ELA',
    value: 0.02,
  },
];

export const latestTransactions = [
  {
    name: 'Data Droidz #001',
    imageUrl: '/image/Phantz Club.svg',
    txhash: '0x651sdfddfsfs...shslf',
    timestamp: '9d ago',
    method: 'Transfer',
    gasfee: '100 ELA',
    value: 0.02,
    owner: '0x221s...BaghLP',
    description: 'First avatar NFT of ESC. Only 100 will be minted ever.',
    from: '0x221s...BaghLP',
    to: '0x3eC....87cD',
  },
  {
    name: 'Data Droidz #002',
    imageUrl: '/image/Data Droidz.svg',
    txhash: '0x651sdfddfsfs...shslf',
    timestamp: '9d ago',
    method: 'Transfer',
    gasfee: '100 ELA',
    value: 0.02,
    owner: '0x221s...BaghLP',
    description: 'First avatar NFT of ESC. Only 100 will be minted ever.',
    from: '0x221s...BaghLP',
    to: '0x3eC....87cD',
  },
  {
    name: 'Data Droidz #003',
    imageUrl: '/image/Bunny Punk.svg',
    txhash: '0x651sdfddfsfs...shslf',
    timestamp: '9d ago',
    method: 'Transfer',
    gasfee: '100 ELA',
    value: 0.02,
    owner: '0x221s...BaghLP',
    description: 'First avatar NFT of ESC. Only 100 will be minted ever.',
    from: '0x221s...BaghLP',
    to: '0x3eC....87cD',
  },
  {
    name: 'Data Droidz #004',
    imageUrl: '/image/Elastos Apes.svg',
    txhash: '0x651sdfddfsfs...shslf',
    timestamp: '9d ago',
    method: 'Transfer',
    gasfee: '100 ELA',
    value: 0.02,
    owner: '0x221s...BaghLP',
    description: 'First avatar NFT of ESC. Only 100 will be minted ever.',
    from: '0x221s...BaghLP',
    to: '0x3eC....87cD',
  },
  {
    name: 'Data Droidz #005',
    imageUrl: '/image/Ela Nugz.svg',
    txhash: '0x651sdfddfsfs...shslf',
    timestamp: '9d ago',
    method: 'Transfer',
    gasfee: '100 ELA',
    value: 0.02,
    owner: '0x221s...BaghLP',
    description: 'First avatar NFT of ESC. Only 100 will be minted ever.',
    from: '0x221s...BaghLP',
    to: '0x3eC....87cD',
  },
];
